# Generated by Django 4.1.7 on 2023-03-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_remove_post_author"),
        ("accounts", "0002_userprofile_organisations"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="posts",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="posts.post",
            ),
        ),
    ]
